[2025-03-18T16:32:21.302+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-18T16:32:21.308+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_hello_world.hello_world manual__2025-03-18T16:30:59.965264+00:00 [queued]>
[2025-03-18T16:32:21.315+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_hello_world.hello_world manual__2025-03-18T16:30:59.965264+00:00 [queued]>
[2025-03-18T16:32:21.315+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-18T16:32:21.335+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): hello_world> on 2025-03-18 16:30:59.965264+00:00
[2025-03-18T16:32:21.338+0000] {standard_task_runner.py:72} INFO - Started process 4521 to run task
[2025-03-18T16:32:21.345+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'simple_hello_world', 'hello_world', 'manual__2025-03-18T16:30:59.965264+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/hello_world.py', '--cfg-path', '/tmp/tmppiu_z1fd']
[2025-03-18T16:32:21.347+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask hello_world
[2025-03-18T16:32:21.400+0000] {task_command.py:467} INFO - Running <TaskInstance: simple_hello_world.hello_world manual__2025-03-18T16:30:59.965264+00:00 [running]> on host LAPTOP-QE9ETVF1.
[2025-03-18T16:32:21.467+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='simple_hello_world' AIRFLOW_CTX_TASK_ID='hello_world' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T16:30:59.965264+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-18T16:30:59.965264+00:00'
[2025-03-18T16:32:21.468+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-18T16:32:21.481+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-18T16:32:21.482+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'Hello World - created a DAG using with Keyword']
[2025-03-18T16:32:21.489+0000] {subprocess.py:99} INFO - Output:
[2025-03-18T16:32:21.554+0000] {subprocess.py:106} INFO - /usr/bin/bash: line 1: Hello: command not found
[2025-03-18T16:32:21.554+0000] {subprocess.py:110} INFO - Command exited with return code 127
[2025-03-18T16:32:21.560+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-03-18T16:32:21.563+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=simple_hello_world, task_id=hello_world, run_id=manual__2025-03-18T16:30:59.965264+00:00, execution_date=20250318T163059, start_date=20250318T163221, end_date=20250318T163221
[2025-03-18T16:32:21.592+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-18T16:32:21.592+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 25 for task hello_world (Bash command failed. The command returned a non-zero exit code 127.; 4521)
Traceback (most recent call last):
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-03-18T16:32:21.638+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-18T16:32:21.651+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-18T16:32:21.651+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
