[2025-03-18T16:27:56.603+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-18T16:27:56.611+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_hello_world.hello_world manual__2025-03-18T16:27:53.665022+00:00 [queued]>
[2025-03-18T16:27:56.619+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_hello_world.hello_world manual__2025-03-18T16:27:53.665022+00:00 [queued]>
[2025-03-18T16:27:56.620+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-18T16:27:56.638+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): hello_world> on 2025-03-18 16:27:53.665022+00:00
[2025-03-18T16:27:56.643+0000] {standard_task_runner.py:72} INFO - Started process 4273 to run task
[2025-03-18T16:27:56.646+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'simple_hello_world', 'hello_world', 'manual__2025-03-18T16:27:53.665022+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/hello_world.py', '--cfg-path', '/tmp/tmph4uowk0s']
[2025-03-18T16:27:56.649+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask hello_world
[2025-03-18T16:27:56.710+0000] {task_command.py:467} INFO - Running <TaskInstance: simple_hello_world.hello_world manual__2025-03-18T16:27:53.665022+00:00 [running]> on host LAPTOP-QE9ETVF1.
[2025-03-18T16:27:56.799+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='simple_hello_world' AIRFLOW_CTX_TASK_ID='hello_world' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T16:27:53.665022+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-18T16:27:53.665022+00:00'
[2025-03-18T16:27:56.801+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-18T16:27:56.820+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-18T16:27:56.821+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', ' "Hello World Once Again"']
[2025-03-18T16:27:56.828+0000] {subprocess.py:99} INFO - Output:
[2025-03-18T16:27:56.884+0000] {subprocess.py:106} INFO - /usr/bin/bash: line 1: Hello World Once Again: command not found
[2025-03-18T16:27:56.884+0000] {subprocess.py:110} INFO - Command exited with return code 127
[2025-03-18T16:27:56.891+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-03-18T16:27:56.896+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=simple_hello_world, task_id=hello_world, run_id=manual__2025-03-18T16:27:53.665022+00:00, execution_date=20250318T162753, start_date=20250318T162756, end_date=20250318T162756
[2025-03-18T16:27:56.925+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-18T16:27:56.925+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 22 for task hello_world (Bash command failed. The command returned a non-zero exit code 127.; 4273)
Traceback (most recent call last):
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/opanggam/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-03-18T16:27:56.941+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-18T16:27:56.951+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-18T16:27:56.952+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
